/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'home-page-settings': HomePageSetting;
    'about-page-settings': AboutPageSetting;
      'product-page-settings': ProductPageSetting;
      'contact-page-settings': ContactPageSetting;
    'general-settings': GeneralSetting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'home-page-settings': HomePageSettingsSelect<false> | HomePageSettingsSelect<true>;
    'about-page-settings': AboutPageSettingsSelect<false> | AboutPageSettingsSelect<true>;
      'product-page-settings': ProductPageSettingsSelect<false> | ProductPageSettingsSelect<true>;
      'contact-page-settings': ContactPageSettingsSelect<false> | ContactPageSettingsSelect<true>;
    'general-settings': GeneralSettingsSelect<false> | GeneralSettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page-settings".
 */
export interface HomePageSetting {
  id: string;
  judul: string;
  slides?:
    | {
        gambar: string | Media;
        label: string;
        judul: string;
        deskripsi: string;
        id?: string | null;
      }[]
    | null;
  tentangKami?: {
    judul: string;
    deskripsi: string;
    gambar: string | Media;
  };
  layananDiHome?:
    | {
        slug: string;
        judul: string;
        deskripsi: string;
        iconName:
          | 'shield'
          | 'globe'
          | 'zap'
          | 'cloud'
          | 'settings'
          | 'monitor-smartphone'
          | 'graduation-cap'
          | 'server'
          | 'database'
          | 'lock'
          | 'wifi'
          | 'cpu'
          | 'hard-drive'
          | 'router'
          | 'network'
          | 'smartphone'
          | 'laptop'
          | 'satellite'
          | 'radio'
          | 'signal'
          | 'gauge'
          | 'layers'
          | 'box'
          | 'briefcase'
          | 'lightning'
          | 'eye'
          | 'check-circle'
          | 'alert-circle'
          | 'info'
          | 'hexagon'
          | 'grid-3x3'
          | 'activity'
          | 'trending'
          | 'trending-up'
          | 'users'
          | 'user'
          | 'award'
          | 'star'
          | 'heart'
          | 'cable'
          | 'bar-chart'
          | 'bar-chart-3';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-settings".
 */
export interface AboutPageSetting {
  id: string;
  judul: string;
  deskripsiSingkat: string;
  tentangPerusahaan?: {
    label: string;
    judul: string;
    paragraf:
      | {
          teks: string;
          id?: string | null;
        }[]
      | null;
    gambar?: {
      utama: string | Media;
      kanan: string | Media;
      bawah: string | Media;
    };
  };
  visiMisi?: {
    label: string;
    visi?: {
      deskripsi: string;
    };
    misi:
      | {
          teks: string;
          id?: string | null;
        }[]
      | null;
    gambar?: (string | Media) | null;
  };
  nilaiInti?: {
    label: string;
    deskripsiSingkat?: string | null;
    nilaiList:
      | {
          huruf: string;
          judul: string;
          subtitle: string;
          deskripsi: string;
          id?: string | null;
        }[]
      | null;
  };
  mengapaMilihGiMS?: {
    label: string;
    judul: string;
    deskripsiSingkat: string;
    alasanList:
      | {
          kategori: string;
          subtitle: string;
          deskripsi: string;
          id?: string | null;
        }[]
      | null;
    gambar: string | Media;
  };
  wilayahJangkauan?: {
    label: string;
    judul: string;
    deskripsi: string;
    kotaList:
      | {
          nama: string;
          latitude: number;
          longitude: number;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-page-settings".
 */
export interface ProductPageSetting {
  id: string;
  judul: string;
  deskripsiSingkat: string;
  kategoriProduk:
    | {
        id: string;
        judul: string;
        gambar: string | Media;
        altGambar: string;
        intro: string;
        produkList?:
          | {
              nama: string;
              deskripsi:
                | {
                    [k: string]: unknown;
                  }
                | unknown[];
              tampilkanKeranjang?: boolean | null;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page-settings".
 */
export interface ContactPageSetting {
  id: string;
  judul: string;
  deskripsiSingkat: string;
  kontakInfo?: {
    alamat: string;
    telepon: string;
    email: string;
  };
  mapLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings".
 */
export interface GeneralSetting {
  id: string;
  namaSitus: string;
  logo?: (string | Media) | null;
  logoFooter?: (string | Media) | null;
  whatsapp?: {
    nomor?: string | null;
    email?: string | null;
    teksGreeting?: string | null;
    labelTombol?: string | null;
    namaPerusahaan?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page-settings_select".
 */
export interface HomePageSettingsSelect<T extends boolean = true> {
  judul?: T;
  slides?:
    | T
    | {
        gambar?: T;
        label?: T;
        judul?: T;
        deskripsi?: T;
      };
  tentangKami?:
    | T
    | {
        judul?: T;
        deskripsi?: T;
        gambar?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-settings_select".
 */
export interface AboutPageSettingsSelect<T extends boolean = true> {
  judul?: T;
  tentangPerusahaan?:
    | T
    | {
        label?: T;
        judul?: T;
        paragraf?: T | { teks?: T };
        gambar?: T | { utama?: T; kanan?: T; bawah?: T };
      };
  visiMisi?:
    | T
    | {
        label?: T;
        visi?: T | { deskripsi?: T };
        misi?: T | { teks?: T };
        gambar?: T;
      };
  nilaiInti?:
    | T
    | {
        label?: T;
        deskripsiSingkat?: T;
        nilaiList?: T | { huruf?: T; judul?: T; subtitle?: T; deskripsi?: T };
      };
  mengapaMilihGiMS?:
    | T
    | {
        label?: T;
        judul?: T;
        deskripsiSingkat?: T;
        alasanList?: T | { kategori?: T; subtitle?: T; deskripsi?: T };
        gambar?: T;
      };
  wilayahJangkauan?:
    | T
    | {
        label?: T;
        judul?: T;
        deskripsi?: T;
        kotaList?: T | { nama?: T; latitude?: T; longitude?: T };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-page-settings_select".
 */
export interface ProductPageSettingsSelect<T extends boolean = true> {
  judul?: T;
  deskripsiSingkat?: T;
  kategoriProduk?:
    | T
    | {
        id?: T;
        judul?: T;
        gambar?: T;
        altGambar?: T;
        intro?: T;
        produkList?: T | { nama?: T; deskripsi?: T; tampilkanKeranjang?: T };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page-settings_select".
 */
export interface ContactPageSettingsSelect<T extends boolean = true> {
  judul?: T;
  deskripsiSingkat?: T;
  kontakInfo?: T | { alamat?: T; telepon?: T; email?: T };
  mapLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  namaSitus?: T;
  logo?: T;
  logoFooter?: T;
  whatsapp?:
    | T
    | {
        nomor?: T;
        email?: T;
        teksGreeting?: T;
        labelTombol?: T;
        namaPerusahaan?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}