import type { CollectionConfig } from 'payload'

export const HomePageSettings: CollectionConfig = {
  slug: 'home-page-settings',
  admin: {
    group: 'Pages',
    useAsTitle: 'judul',
    defaultColumns: ['judul', 'updatedAt'],
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'judul',
      type: 'text',
      required: true,
      label: 'Judul Halaman',
    },
    {
      name: 'slides',
      type: 'array',
      label: 'Slide Carousel',
      fields: [
        {
          name: 'gambar',
          type: 'relationship',
          relationTo: 'media',
          required: true,
          label: 'Gambar Slide',
        },
        {
          name: 'label',
          type: 'text',
          required: true,
          label: 'Label',
        },
        {
          name: 'judul',
          type: 'text',
          required: true,
          label: 'Judul Slide',
        },
        {
          name: 'deskripsi',
          type: 'textarea',
          required: true,
          label: 'Deskripsi',
        },
      ],
    },
    {
      name: 'tentangKami',
      type: 'group',
      label: 'Bagian Tentang Kami',
      fields: [
        {
          name: 'judul',
          type: 'text',
          required: true,
          label: 'Judul',
        },
        {
          name: 'deskripsi',
          type: 'textarea',
          required: true,
          label: 'Deskripsi Singkat',
        },
        {
          name: 'gambar',
          type: 'relationship',
          relationTo: 'media',
          required: true,
          label: 'Gambar',
        },
      ],
    },
    {
      name: 'layananDiHome',
      type: 'array',
      label: 'Layanan di Home Page',
      fields: [
        {
          name: 'slug',
          type: 'text',
          required: true,
          label: 'Slug Layanan',
        },
        {
          name: 'judul',
          type: 'text',
          required: true,
          label: 'Judul Layanan',
        },
        {
          name: 'deskripsi',
          type: 'textarea',
          required: true,
          label: 'Deskripsi Singkat',
        },
        {
          name: 'iconName',
          type: 'select',
          required: true,
          label: 'Icon Layanan (Lucide React)',
          options: [
            { label: 'Shield', value: 'shield' },
            { label: 'Globe', value: 'globe' },
            { label: 'Zap', value: 'zap' },
            { label: 'Cloud', value: 'cloud' },
            { label: 'Settings', value: 'settings' },
            { label: 'Monitor/Smartphone', value: 'monitor-smartphone' },
            { label: 'Graduation Cap', value: 'graduation-cap' },
            { label: 'Server', value: 'server' },
            { label: 'Database', value: 'database' },
            { label: 'Lock', value: 'lock' },
            { label: 'WiFi', value: 'wifi' },
            { label: 'CPU', value: 'cpu' },
            { label: 'Hard Drive', value: 'hard-drive' },
            { label: 'Router', value: 'router' },
            { label: 'Network', value: 'network' },
            { label: 'Smartphone', value: 'smartphone' },
            { label: 'Laptop', value: 'laptop' },
            { label: 'Satellite', value: 'satellite' },
            { label: 'Radio', value: 'radio' },
            { label: 'Signal', value: 'signal' },
            { label: 'Gauge', value: 'gauge' },
            { label: 'Layers', value: 'layers' },
            { label: 'Box', value: 'box' },
            { label: 'Briefcase', value: 'briefcase' },
            { label: 'Lightning', value: 'lightning' },
            { label: 'Eye', value: 'eye' },
            { label: 'Check Circle', value: 'check-circle' },
            { label: 'Alert Circle', value: 'alert-circle' },
            { label: 'Info', value: 'info' },
            { label: 'Hexagon', value: 'hexagon' },
            { label: 'Grid 3x3', value: 'grid-3x3' },
            { label: 'Activity', value: 'activity' },
            { label: 'Trending', value: 'trending' },
            { label: 'Trending Up', value: 'trending-up' },
            { label: 'Users', value: 'users' },
            { label: 'User', value: 'user' },
            { label: 'Award', value: 'award' },
            { label: 'Star', value: 'star' },
            { label: 'Heart', value: 'heart' },
            { label: 'Cable', value: 'cable' },
            { label: 'Bar Chart', value: 'bar-chart' },
            { label: 'Bar Chart 3', value: 'bar-chart-3' },
          ],
        },
      ],
      minRows: 1,
    },
  ],
}
